components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ScanRequest:
      properties:
        git_url:
          anyOf:
          - type: string
          - type: 'null'
          title: Git Url
        language:
          title: Language
          type: string
        path:
          anyOf:
          - type: string
          - type: 'null'
          title: Path
        project_name:
          title: Project Name
          type: string
      required:
      - project_name
      - language
      title: ScanRequest
      type: object
    ValidationError:
      properties:
        ctx:
          title: Context
          type: object
        input:
          title: Input
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: Green-AI Agent Dashboard
  version: 0.1.0
openapi: 3.1.0
paths:
  /:
    get:
      operationId: dashboard__get
      responses:
        '200':
          content:
            text/html:
              schema:
                type: string
          description: Successful Response
      summary: Dashboard
  /api/calibrate:
    get:
      operationId: api_calibrate_api_calibrate_post
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Api Calibrate
    post:
      operationId: api_calibrate_api_calibrate_post
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Api Calibrate
  /api/charts:
    get:
      operationId: api_charts_api_charts_get
      responses:
        '200':
          content:
            application/json:
              schema:
                title: Response Api Charts Api Charts Get
          description: Successful Response
      summary: Api Charts
  /api/compare:
    get:
      operationId: api_compare_scans_api_compare_get
      parameters:
      - in: query
        name: project
        required: true
        schema:
          title: Project
          type: string
      - in: query
        name: scan1
        required: false
        schema:
          default: -2
          title: Scan1
          type: integer
      - in: query
        name: scan2
        required: false
        schema:
          default: -1
          title: Scan2
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                title: Response Api Compare Scans Api Compare Get
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Api Compare Scans
  /api/export/csv:
    get:
      operationId: api_export_csv_api_export_csv_get
      parameters:
      - in: query
        name: project
        required: false
        schema:
          default: Scan
          title: Project
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Api Export Csv
  /api/export/html:
    get:
      operationId: api_export_html_api_export_html_get
      parameters:
      - in: query
        name: project
        required: false
        schema:
          default: Scan
          title: Project
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Api Export Html
  /api/history:
    get:
      operationId: api_get_history_api_history_get
      parameters:
      - in: query
        name: project
        required: true
        schema:
          title: Project
          type: string
      - in: query
        name: days
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          title: Days
      responses:
        '200':
          content:
            application/json:
              schema:
                title: Response Api Get History Api History Get
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Api Get History
  /api/projects:
    get:
      operationId: api_projects_list_api_projects_get
      responses:
        '200':
          content:
            application/json:
              schema:
                title: Response Api Projects List Api Projects Get
          description: Successful Response
      summary: Api Projects List
  /api/projects/comparison:
    get:
      operationId: api_projects_comparison_api_projects_comparison_get
      parameters:
      - in: query
        name: projects
        required: false
        schema:
          items:
            type: string
          title: Projects
          type: array
      responses:
        '200':
          content:
            application/json:
              schema:
                title: Response Api Projects Comparison Api Projects Comparison Get
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Api Projects Comparison
  /api/projects/{project_name}:
    delete:
      operationId: api_delete_project_api_projects__project_name__delete
      parameters:
      - in: path
        name: project_name
        required: true
        schema:
          title: Project Name
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Api Delete Project
    get:
      operationId: api_project_detail_api_projects__project_name__get
      parameters:
      - in: path
        name: project_name
        required: true
        schema:
          title: Project Name
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                title: Response Api Project Detail Api Projects  Project Name  Get
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Api Project Detail
  /api/projects/{project_name}/clear:
    post:
      operationId: api_clear_project_api_projects__project_name__clear_post
      parameters:
      - in: path
        name: project_name
        required: true
        schema:
          title: Project Name
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Api Clear Project
  /api/projects/{project_name}/rescan:
    post:
      operationId: api_rescan_project_api_projects__project_name__rescan_post
      parameters:
      - in: path
        name: project_name
        required: true
        schema:
          title: Project Name
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Api Rescan Project
  /api/remediation/preview:
    get:
      operationId: api_remediation_preview_api_remediation_preview_get
      parameters:
      - in: query
        name: project
        required: true
        schema:
          title: Project
          type: string
      - in: query
        name: file
        required: true
        schema:
          title: File
          type: string
      - in: query
        name: line
        required: true
        schema:
          title: Line
          type: integer
      - in: query
        name: issue_id
        required: true
        schema:
          title: Issue Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Api Remediation Preview
  /api/results:
    get:
      operationId: api_results_api_results_get
      responses:
        '200':
          content:
            application/json:
              schema:
                title: Response Api Results Api Results Get
          description: Successful Response
      summary: Api Results
  /api/rules/{rule_id}/disable:
    post:
      operationId: api_disable_rule_api_rules__rule_id__disable_post
      parameters:
      - in: path
        name: rule_id
        required: true
        schema:
          title: Rule Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Api Disable Rule
  /api/rules/{rule_id}/enable:
    post:
      operationId: api_enable_rule_api_rules__rule_id__enable_post
      parameters:
      - in: path
        name: rule_id
        required: true
        schema:
          title: Rule Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Api Enable Rule
  /api/scan:
    post:
      operationId: api_scan_api_scan_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScanRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Api Scan
  /api/standards:
    get:
      operationId: api_standards_list_api_standards_get
      responses:
        '200':
          content:
            application/json:
              schema:
                title: Response Api Standards List Api Standards Get
          description: Successful Response
      summary: Api Standards List
  /api/standards/{standard_name}/disable:
    post:
      operationId: api_disable_standard_api_standards__standard_name__disable_post
      parameters:
      - in: path
        name: standard_name
        required: true
        schema:
          title: Standard Name
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Api Disable Standard
  /api/standards/{standard_name}/enable:
    post:
      operationId: api_enable_standard_api_standards__standard_name__enable_post
      parameters:
      - in: path
        name: standard_name
        required: true
        schema:
          title: Standard Name
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Api Enable Standard
  /api/standards/{standard_name}/rules:
    get:
      operationId: api_standard_rules_api_standards__standard_name__rules_get
      parameters:
      - in: path
        name: standard_name
        required: true
        schema:
          title: Standard Name
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                title: Response Api Standard Rules Api Standards  Standard Name  Rules
                  Get
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Api Standard Rules
  /api/telemetry:
    get:
      operationId: api_telemetry_api_telemetry_get
      responses:
        '200':
          content:
            application/json:
              schema:
                title: Response Api Telemetry Api Telemetry Get
          description: Successful Response
      summary: Api Telemetry
  /api/trending:
    get:
      operationId: api_get_trending_api_trending_get
      parameters:
      - in: query
        name: project
        required: true
        schema:
          title: Project
          type: string
      - in: query
        name: days
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          title: Days
      responses:
        '200':
          content:
            application/json:
              schema:
                title: Response Api Get Trending Api Trending Get
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Api Get Trending
